name: jsnail_list
description: Universal list.
version: 0.0.1
homepage: https://github.com/Snailapp/JSnail

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: